name: kalimati
description: "Kalimati App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  floor: ^1.5.0
  riverpod: ^3.0.3
  flutter_tts: ^4.2.3
  uuid: ^4.5.2
  video_player: ^2.10.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/packages.json
    - assets/data/users.json