name: supabase_app
description: "Supabase example"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  flutter_riverpod: ^3.0.3
  http: ^1.5.0
  go_router: ^16.3.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/